version: "3.9"
services:

  # main mlflow server
  server:
    build: ./mlflow
    ports:
      - "127.0.0.1:6000:5000"
    restart: always
    environment:
      - STORE_URI=mysql://mlflow:mlflow@backend-store:3306/mlflow
    links:
      - backend-store
    volumes:
      - artifacts:/artifacts
    command: --host 0.0.0.0 --backend-store-uri mysql://mlflow:mlflow@backend-store:3306/mlflow --serve-artifacts --artifacts-destination /artifacts
  
  # MySQL database
  backend-store:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mlflow-server-pwd
      - MYSQL_USER=mlflow
      - MYSQL_PASSWORD=mlflow
      - MYSQL_DATABASE=mlflow
    volumes:
      - db:/val/lib/mysql

volumes:
  db:
  artifacts:
