version: "3.9"
services:

  # main mlflow server
  server:
    build: ./mlflow
    container_name: mlflow-server
    ports:
      - "127.0.0.1:9999:5000"
    restart: always
    environment:
      - STORE_URI=mysql://mlflow:mlflow@backend-store:3306/mlflow
    links:
      - backend-store
    volumes:
      - artifacts:/artifacts
    command: >-
      server
      --host 0.0.0.0
      --backend-store-uri mysql://mlflow:mlflow@backend-store:3306/mlflow
      --serve-artifacts --artifacts-destination /artifacts
      --app-name basic-auth
  
  # MySQL database
  backend-store:
    image: mysql:8.0.29-debian
    container_name: mlflow-backend-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mlflow-server-pwd
      - MYSQL_USER=mlflow
      - MYSQL_PASSWORD=mlflow
      - MYSQL_DATABASE=mlflow
    volumes:
      - db:/var/lib/mysql
    cap_add:
      - SYS_NICE   # CAP_SYS_NICE

volumes:
  db:
  artifacts:
